---
title: Analysis
description:
toc: true
featuredVideo:
featuredImage: https://www.kff.org/wp-content/uploads/2018/10/9256-figure-1.png
draft: false
---


<div id="TOC">

</div>

<div id="motivation-for-our-data-analysis-eda" class="section level2">
<h2>Motivation for our Data Analysis (EDA)</h2>
<p>Medicare is a national health insurance program in the United States that provides coverage to the elderly and people with disabilities. In 1965, after the legislation was signed by President Lyndon B Johnson, Americans started receiving Medicare health coverage and medical insurance benefits first took effect. After more than 5 decades, by august 2022, there were nearly 65 million people receiving health coverage through Medicare. Nowadays, medicare spending account for about 20% of total national health spending per year. To be eligible for Medicare coverage, individuals must be 65 years of age or older and have paid into the Medicare system through their taxes while working. We are interested in medicare payment because Medicare spending in the United States has increased significantly in recent years —- increased by more than $200 billion since 2010. In addition, it is also a significant part (15.3%) of the overall healthcare spending. With the aging population, Medicare spending is projected to increase significantly over the next decade.</p>
<p>Thus, in the project, we aim to explore factors that make U.S. healthcare so expensive by focusing on medicare spending because it is one of the largest sources of healthcare funding in the country. To make the project manageable, we decided to focus on inpatient Medicare spending due to data availability.</p>
</div>
<div id="breadth-of-eda" class="section level2">
<h2>Breadth of EDA</h2>
<p>During initial data analysis, we analyzed <a href="https://data.cms.gov/provider-summary-by-type-of-service/medicare-inpatient-hospitals/medicare-inpatient-hospitals-by-provider-and-service">Medicare Inpatient Hospitals by Provider and Service</a>. We first explored the relationship between Average medicare Payment and average total payments.</p>
<div id="plot-1-the-relationship-between-average-medicare-payments-and-average-total-payments" class="section level3">
<h3>Plot 1: The relationship between Average Medicare Payments and Average Total Payments</h3>
<p>We first examined the relationship between medicare payment and total payment.</p>
<p><img src="/analysis_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<p>The Medicare covered payment increases as the total payment increases. This makes sense because Medicare covers payment mostly by a certain percentage, but may vary depending on differences in hospital charge structures. In the graph, each datapoint represents one state. From the graph, you can see Mean Medicare Payment varies in states with some states’ values cluster together. If you examine closely, you will realize the ratio of Medicare Payment and Total Payment also varies by state. For the next two plots, we explored Medicare payments and the ratio between Medicare payment and Total Payment in each states.</p>
</div>
<div id="plot-2-the-ratio-of-medicare-payment-and-total-payment-for-each-state" class="section level3">
<h3>Plot 2: The ratio of medicare payment and total payment for each state</h3>
<p>Next, we zoom in to see if the ratio of medicare payment and total payment varies across states.</p>
<p><img src="/analysis_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>Washington DC and Hawaii have the lowest ratio of medical payment and total payment while South Dakota and Maryland have the highest ratio. From the above graph that describes the percentage the Medicare payment in the total payment, it’s quite clear that there’s a standard of 85% that can be found within all the states in the U.S. However, it’s quite surprising to find that there are almost half of the states do not fulfill this standard. To be more specific, it means the residents of these states have to afford 15-25% of the total payment even if they have medicare covered. Also, there are states that covered more than 90% of the payment which means the person only has to afford less than 10% of the total payment. The disparity is visually huge among all the states and it is something that could be further analyzed to see if there’s a need to improve the Medicare system in each state.</p>
</div>
<div id="plot-3-mean-medicare-payment-in-u.s.-states" class="section level3">
<h3>Plot 3: Mean Medicare payment in U.S. States</h3>
<p><img src="/analysis_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>Theoretically, Medicare coverage should be the same across all states in the United States. Since it is a national program, the benefits and services it covers should be standardized, meaning that an individual who is enrolled in Medicare in one state will have the same coverage as someone who is enrolled in Medicare in another state. However, during initial exploratory data analysis, we found that average medicare payment varies greatly from state to state. As a result, we decided to shift our focus to understand the sources of variation in medicare payment across different geographic areas and identify sources that have the largest impact on medicare payment variations. We conducted some literature reviews and identified various possible factors including premium, geographic practice cost indices, length of stay, readmission rate, health status, income level, race, poverty rate, GDP, cover charged, and hierarchical condition category (HCC).</p>
</div>
<div id="plot-4-medicare-coverage-vs.-length-of-stay-in-hospital" class="section level3">
<h3>Plot 4: Medicare Coverage vs. Length of stay in hospital</h3>
<p><img src="/analysis_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>We further examined the relationship between Medicare coverage(Medicare payment/total payment) and length of stay in hospital. We summarized the medicare coverage of each state and merge with data of average length of stay in hospital of people with medicare in each state. Then, we plotted the relationship between Medicare coverage and average length of stay. As shown above, there is a negative relationship between Medicare coverage and average length of stay, implying that Medicare pays a higher percentage to doctors’ wage in states with shorter patient lengths of stay. This is because when a patient stays in the hospital longer, more of the Medicare payment goes to pay for medicines, medical equipment, treatments, etc., so the doctor gets a smaller percentage of the Medicare payment.</p>
</div>
</div>
<div id="depth-of-eda" class="section level2">
<h2>Depth of EDA</h2>
<div id="factor-i-medicare-payment-vs.-premium" class="section level3">
<h3>Factor I: Medicare Payment vs. Premium</h3>
<p><img src="/analysis_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p><img src="/analysis_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>The first plot shows the regression plot between premium and medicare Payment. There is a positive regression relationship between the two variables, indicating that Medicare Payment increases as Premium increases. However, when we wanted to explore Medicare payment data for each state and reordered by premium, we saw no apparent patterns among the states. Although there is a positive relationship indicated in the regression plot, there is no obvious pattern shown in the boxplot. Therefore, we cannot conclude that medicare Payment goes up with the increase in premium. In other words, more expensive medicare premium does not bring greater medicare Payment, and cheaper premium does not lower the payment either.</p>
</div>
<div id="factor-ii-medicare-payment-vs.-gdp" class="section level3">
<h3>Factor II: Medicare Payment vs. GDP</h3>
<p><img src="/analysis_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Then We decide to investigate the relationship between GDP and Medicare Payment since we believe that a state with higher GDP has more expensive medical care, and medicare payment should also rise to cover the corresponding inflation. According to the plot above, medicare payment increases as GDP goes up, which means that the average medicare payment for each beneficiary is positively correlated with the GDP of the state where the beneficiary resides. This observation could be potentially explained by the fact that GDP could impact the cost of living. As GDP increases, the cost of living may also increase, which could lead to higher prices for medical goods and services. If the cost of providing medical care increases, Medicare may need to adjust its payment rates in order to cover these costs.</p>
</div>
<div id="factor-iii-medicare-payment-vs-hierarchical-condition-category-hcc" class="section level3">
<h3>Factor III: Medicare Payment vs Hierarchical Condition Category (HCC)</h3>
<p><img src="/analysis_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Hierarchical condition category (HCC) is a coding system that is used in the United States to classify medical conditions for the purpose of determining the amount of reimbursement that a healthcare provider will receive from Medicare. Higher HCC score means the providers will receive higher reimbursement. There is one obvious outlier, which is DC, it has high Medicare payment but low HCC score. As indicated in the graph, there is limited relationship between Medicare payment and HCC.</p>
</div>
<div id="factor-iv-medicare-payment-vs-readmission-rate" class="section level3">
<h3>Factor IV: Medicare Payment vs Readmission Rate</h3>
<p><img src="/analysis_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>Readmission rate is the percentage of patients who are admitted to a hospital again within a certain period of time after being discharged. This rate is often used as a measure of the quality of care provided by a hospital, as higher readmission rates may indicate that patients are not receiving the care they need to prevent their condition from worsening or recurring. Starting 2012, the Hospital Readmissions Reduction Program (HRRP) reduces at max three percent of Medicare payment for hopsitals that have high 30 days readmission rate. There is also limited relationship between Readmission Rate and Medicare Payment shown in this graph.</p>
</div>
<div id="factor-v-medicare-payment-vs-length-of-stay" class="section level3">
<h3>Factor V: Medicare Payment vs Length of Stay</h3>
<p><img src="/analysis_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>We further examined the relationship between medicare payment and length of stay in hospital. We summarized the medicare payment of each state and merge with data of average length of stay in hospital of people with medicare in each state. Then, we plotted the relationship between Medicare payment and average length of stay. As shown above, there is a negative relationship between Medicare payment and average length of stay, implying that Medicare pays a higher percentage to doctors’ wage in states with shorter patient lengths of stay. This is because when a patient stays in the hospital longer, more of the Medicare payment goes to pay for medicines, medical equipment, treatments, etc., so the doctor gets a smaller percentage of the Medicare payment.</p>
</div>
<div id="factor-vi-medicare-payment-vs-health-status" class="section level3">
<h3>Factor VI: Medicare Payment VS Health Status</h3>
<p><img src="/analysis_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>The result is surprising. We expect a negative relationship because the health status of an individual should affect the overall cost of the care. People with chronic illness may require more frequently and costly medical intervention than people who are in good health, thus their medicare payment should be higher. But the graph shows opposite relationship that better health status results in higher medicare payment.</p>
</div>
<div id="factor-vii-medicare-payment-vs-geographic-practice-cost-index" class="section level3">
<h3>Factor VII: Medicare Payment VS Geographic Practice Cost Index</h3>
<p><img src="/analysis_files/figure-html/unnamed-chunk-14-1.png" width="672" />
The Geographic Practice Cost Index (GPCI) is the factor used by the Centers for Medicare &amp; Medicaid Services (CMS) to adjust payment rates based on the relative cost of providing these services in different areas of the country. The GPCI takes into account differences in the cost of labor, rent, and other expenses associated with providing medical services in different regions. The graph shows a positive relationship, meaning that if the GPCI for a certain area is higher than the national average, Medicare payment will be adjusted upward to reflect the higher cost of providing those services in that location. Conversely, if the GPCI for a certain area is lower than the national average,Medicare payment for services provided in that area will be adjusted downward.</p>
</div>
</div>
<div id="flaws-and-limitations-of-eda" class="section level2">
<h2>Flaws and Limitations of EDA</h2>
<p>First, due to the availability of the database, we were unable to obtain data from more years, which resulted in our data being insufficient to analyze and obtain any long-term effects. Secondly, it was difficult for us to use the raw data set for the analysis of some factors, which resulted in our dataset not being large enough, so we obtained several not ideal correlations. In addition, in real life, Medicare payment is a variable that is influenced by so many factors, so any single variable on Medicare payment would not be very significant. We need to collect and analyze more factors that may affect Medicare payment for the analysis.</p>
</div>
<div id="modeling" class="section level2">
<h2>Modeling</h2>
<div id="motivations-for-modeling" class="section level3">
<h3>Motivations for modeling</h3>
<p>After observing the relationships between variables through EDA, we plan to creates a model that could help us predict medicare payment. This modeling&amp;prediction sections involves four main parts: datasets, correlation, optimal model selection, and predicition.</p>
</div>
<div id="create-training-and-testing-datasets" class="section level3">
<h3>Create training and testing datasets</h3>
<p>We first collect all our 2019 datasets and combine them together to create the trainning dataset called “Train” and combined all our 2020 datasets to create the testing dataset called “Test”. Again, we only have 51 observations since we need to merge all out datasets by the common variables “state” and there are only 51 states in the U.S. We choose Medicare Payment as our output, aim to figure out which variables affect Medicare Payment the most, and use the optimal model to predict Medicare Payment. Our initial x variables include GDP, all the GPCI’s, Lenth of state (LOS), Health_Status, Average Hierarchical Condition Category variables BENE_AVG_RISK_SCRE and ACUTE_HOSP_READMSN_PCT.</p>
</div>
<div id="correlation-matrix" class="section level3">
<h3>Correlation Matrix</h3>
<p>In order to have a deeper understanding of the correlations between variables, we then create the scatterplot matrix of all the variables, figuring out which variables have the biggest correlation with Mean_Medicare_Payment.
<img src="/analysis_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>According to the graph, PE_GPCI seems like the one with the highest correlation with Medicare Payment, with 0.42. GDP, PW_GPCI, and Health Ststus are another variables that also indicate strong relationships with Medicare Payment.</p>
</div>
<div id="simple-linear-regression-1" class="section level3">
<h3>Simple Linear Regression 1</h3>
<pre><code>## 
## Call:
## lm(formula = Mean_Medicare_Payment ~ ., data = Train)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3236.8  -809.9  -108.1   738.6  5809.2 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)            -1.644e+04  5.387e+03  -3.052  0.00394 ** 
## LOS                     1.514e+02  5.480e+02   0.276  0.78375    
## PW_GPCI                 1.053e+04  3.632e+03   2.900  0.00592 ** 
## PE_GPCI                 1.911e+04  4.152e+03   4.604 3.81e-05 ***
## MP_GPCI                 2.255e+02  6.106e+02   0.369  0.71375    
## Health_Status          -4.366e+02  7.431e+03  -0.059  0.95342    
## GDP                     4.095e-04  5.627e-04   0.728  0.47078    
## BENE_AVG_RISK_SCRE      9.024e+03  4.792e+03   1.883  0.06660 .  
## ACUTE_HOSP_READMSN_PCT -5.298e+04  2.063e+04  -2.569  0.01385 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1497 on 42 degrees of freedom
## Multiple R-squared:  0.6795, Adjusted R-squared:  0.6184 
## F-statistic: 11.13 on 8 and 42 DF,  p-value: 2.842e-08</code></pre>
<p>We first fit a linear regression model on our output Medicare Payment with all other x variables. We get a F-statistics of 11.13 p-value of 0.06286, which is much less than 0.05. The adjusted R-squared of 0.6184, which says that 61.84% of the variance in the training set is explained by the model. According to the t-test, most of the p-values are greater than 0.05, such as those of GPCI, indicating that they have little impact of Medicare Payment. However, variables like PW_GPCI and PE_GPCI have very low p-values, which shows that they might have greater affects on Medicare Payment, and it aligns with out conclusions in the scatter matrix part.</p>
</div>
<div id="model-selection" class="section level3">
<h3>Model Selection</h3>
<p>Model selection is extremely important in modeling analysis since choosing the right variables can help you find the optimal model. Even though we have already done the correlation matrix and T-test to find variables that had big influence on medicare payment, it is still significant to apply more technical methods to find the optimal model. Here we first use the step-wise AIC on our simple regression model 1, which can help us measure the bias-variance trade-off.</p>
<pre><code>## Start:  AIC=753.87
## Mean_Medicare_Payment ~ LOS + PW_GPCI + PE_GPCI + MP_GPCI + Health_Status + 
##     GDP + BENE_AVG_RISK_SCRE + ACUTE_HOSP_READMSN_PCT
## 
##                          Df Sum of Sq       RSS    AIC
## - Health_Status           1      7742  94181291 751.87
## - LOS                     1    171057  94344607 751.96
## - MP_GPCI                 1    305828  94479378 752.04
## - GDP                     1   1187653  95361202 752.51
## &lt;none&gt;                                 94173549 753.87
## - BENE_AVG_RISK_SCRE      1   7952293 102125842 756.00
## - ACUTE_HOSP_READMSN_PCT  1  14796223 108969772 759.31
## - PW_GPCI                 1  18852352 113025901 761.18
## - PE_GPCI                 1  47527631 141701181 772.71
## 
## Step:  AIC=751.87
## Mean_Medicare_Payment ~ LOS + PW_GPCI + PE_GPCI + MP_GPCI + GDP + 
##     BENE_AVG_RISK_SCRE + ACUTE_HOSP_READMSN_PCT
## 
##                          Df Sum of Sq       RSS    AIC
## - LOS                     1    205243  94386534 749.99
## - MP_GPCI                 1    303740  94485031 750.04
## - GDP                     1   1567226  95748517 750.72
## &lt;none&gt;                                 94181291 751.87
## + Health_Status           1      7742  94173549 753.87
## - BENE_AVG_RISK_SCRE      1   7979576 102160867 754.02
## - ACUTE_HOSP_READMSN_PCT  1  14885687 109066978 757.36
## - PW_GPCI                 1  18986306 113167597 759.24
## - PE_GPCI                 1  93311337 187492628 784.99
## 
## Step:  AIC=749.99
## Mean_Medicare_Payment ~ PW_GPCI + PE_GPCI + MP_GPCI + GDP + BENE_AVG_RISK_SCRE + 
##     ACUTE_HOSP_READMSN_PCT
## 
##                          Df Sum of Sq       RSS    AIC
## - MP_GPCI                 1    262901  94649435 748.13
## - GDP                     1   1363504  95750039 748.72
## &lt;none&gt;                                 94386534 749.99
## + LOS                     1    205243  94181291 751.87
## + Health_Status           1     41927  94344607 751.96
## - BENE_AVG_RISK_SCRE      1   8148022 102534556 752.21
## - ACUTE_HOSP_READMSN_PCT  1  15749902 110136437 755.86
## - PW_GPCI                 1  24540287 118926822 759.77
## - PE_GPCI                 1  93862873 188249407 783.19
## 
## Step:  AIC=748.13
## Mean_Medicare_Payment ~ PW_GPCI + PE_GPCI + GDP + BENE_AVG_RISK_SCRE + 
##     ACUTE_HOSP_READMSN_PCT
## 
##                          Df Sum of Sq       RSS    AIC
## - GDP                     1   1449441  96098876 746.90
## &lt;none&gt;                                 94649435 748.13
## + MP_GPCI                 1    262901  94386534 749.99
## + LOS                     1    164404  94485031 750.04
## + Health_Status           1     32724  94616711 750.11
## - BENE_AVG_RISK_SCRE      1   8119729 102769164 750.32
## - ACUTE_HOSP_READMSN_PCT  1  15499921 110149356 753.86
## - PW_GPCI                 1  24281882 118931317 757.77
## - PE_GPCI                 1  99300534 193949969 782.72
## 
## Step:  AIC=746.9
## Mean_Medicare_Payment ~ PW_GPCI + PE_GPCI + BENE_AVG_RISK_SCRE + 
##     ACUTE_HOSP_READMSN_PCT
## 
##                          Df Sum of Sq       RSS    AIC
## &lt;none&gt;                                 96098876 746.90
## + GDP                     1   1449441  94649435 748.13
## + Health_Status           1    374305  95724571 748.70
## + MP_GPCI                 1    348837  95750039 748.72
## + LOS                     1       566  96098310 748.90
## - BENE_AVG_RISK_SCRE      1  10032270 106131146 749.97
## - ACUTE_HOSP_READMSN_PCT  1  16953747 113052624 753.19
## - PW_GPCI                 1  23461910 119560786 756.04
## - PE_GPCI                 1 120199703 216298579 786.28</code></pre>
<p>The result shows that the optimal model is Mean_Medicare_Payment ~ PW_GPCI + PE_GPCI + BENE_AVG_RISK_SCRE + ACUTE_HOSP_READMSN_PCT, with athe lowest AIC of 746.9</p>
<pre><code>## 
## Call:
## lm(formula = Mean_Medicare_Payment ~ PW_GPCI + PE_GPCI + BENE_AVG_RISK_SCRE + 
##     ACUTE_HOSP_READMSN_PCT, data = Train)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3396.2  -694.2  -165.0   753.5  5819.1 
## 
## Coefficients:
##                        Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)              -17517       4507  -3.886 0.000325 ***
## PW_GPCI                   10659       3181   3.351 0.001616 ** 
## PE_GPCI                   19928       2627   7.585 1.22e-09 ***
## BENE_AVG_RISK_SCRE         9894       4515   2.191 0.033526 *  
## ACUTE_HOSP_READMSN_PCT   -51427      18053  -2.849 0.006543 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1445 on 46 degrees of freedom
## Multiple R-squared:  0.6729, Adjusted R-squared:  0.6445 
## F-statistic: 23.66 on 4 and 46 DF,  p-value: 1.131e-10</code></pre>
<p>Based on our model selection analysis, we choose Mean_Medicare_Payment ~ PW_GPCI + PE_GPCI + BENE_AVG_RISK_SCRE + ACUTE_HOSP_READMSN_PCT as our optimal model and get a p-value of 1.131e-10 in the F-test, which indicates that our model is statistically significant. According to the T-test, all three variables have relatively low p-values, and our adjusted R-squared is 0.6445, which is much higher than the initial model.</p>
</div>
<div id="constant-variance-assumption" class="section level3">
<h3>Constant variance assumption</h3>
<p>It is important to check whether the statistical assumptions hold for our model. We first check the constant variance assumption by plotting standardized residuals with outputs.
<img src="/analysis_files/figure-html/unnamed-chunk-20-1.png" width="672" />
According to the graph, constant variance assumption holds since there is no pattern shown. It is also necessary to check the normality assumption; therefore, we graphed the normal QQ-plot and Histogram plot.</p>
<p><img src="/analysis_files/figure-html/unnamed-chunk-21-1.png" width="672" /><img src="/analysis_files/figure-html/unnamed-chunk-21-2.png" width="672" /></p>
<p>Based on the normal QQ-plot, there are a few outliers, but the normality assumption is not violated. Even though the histogram does show normality, we think this is because we only have 51 observations.</p>
</div>
<div id="linear-regression-model-prediction" class="section level3">
<h3>Linear Regression Model Prediction</h3>
<p>After checking the statistical assumptions, it’s time to perform predictions based on our model Mean_Medicare_Payment ~ PW_GPCI + PE_GPCI + BENE_AVG_RISK_SCRE + ACUTE_HOSP_READMSN_PCT.
<img src="/analysis_files/figure-html/unnamed-chunk-22-1.png" width="672" /><img src="/analysis_files/figure-html/unnamed-chunk-22-2.png" width="672" />
The linear regression model gives us a MSE of 2199525 and RMSE of 0.01131751. Our prediction in the Validation Medicare Payment vs Prediction graph fits well in the actual data. Also, in the further comparisons, the prediction graph also shows our indication works well since most of the extreme values are captured by our model. Moreover, the low relative mean square error also indicates that our model could make good predictions on medicare payment.</p>
</div>
<div id="xgboost-prediction" class="section level3">
<h3>XGboost Prediction</h3>
<p>We then decide to perform a more advanced prediction method, XGboost regression, to predict medicare payment.
<img src="/analysis_files/figure-html/unnamed-chunk-23-1.png" width="672" /><img src="/analysis_files/figure-html/unnamed-chunk-23-2.png" width="672" />
This model gives us a MSE of 1033343 and RMSE of 0.005316997, which is much lower than the linear regression one. The graphs also show that XGBoost could catch all the extreme values. However, a drawback of the XGBoost approach is that machine learning models like this one are somewhat opaque in terms of how the algorithm works, making it challenging for us to pinpoint precisely which predictors are the strongest contributors and why.</p>
</div>
</div>
