---
title: Model & Prediction
description:
toc: true
authors: []
tags: []
categories: []
series: []
date: 2022-12-12T19:58:14-05:00
lastmod: 2022-12-12T19:58:14-05:00
featuredVideo:
featuredImage:
draft: false
---
```{r}
library(tidyverse)
Train <- read_csv(here::here("dataset","total.csv"),col_types = cols_only(Medicare_Coverage=col_number(),year=col_number(),LOS=col_number(),state=col_character()))
Train <- Train %>% filter(year==2019)
population_Train <- read_csv(here::here("dataset","population.csv"),col_types = cols_only(state=col_character(),Year2019=col_number()))
hs_Train <- read_csv(here::here("dataset","HS2019.csv"), )
GDP_Train <- read_csv(here::here("dataset","GDP2019.csv"))
GPCI_Train <- read_csv(here::here("dataset","GPCI2019.csv"))
GPCI_Train<-GPCI_Train %>% group_by(state) %>% summarise(PW_GPCI=mean(PW_GPCI),PE_GPCI=mean(PE_GPCI),MP_GPCI=mean(MP_GPCI))
df_list <- list(GPCI_Train,Train,hs_Train,GDP_Train,population_Train)
Train <- df_list %>% reduce(full_join,by='state')
Train <- Train%>% select(PW_GPCI:Medicare_Coverage,status,GDP,Year2019) %>% head(-1)
write_csv(Train, file = here::here("dataset", "Training.csv"))
save(Train, file = here::here("dataset/Training.RData"))

```
We first collect all out 2019 datasets and combine them together to create the trainning dataset called "Train"

```{r}
library(GGally)
ggpairs(Train,upper = list(continuous = wrap("points", alpha = 0.3,size=0.1)),
        lower = list(continuous = wrap('cor', size = 4)))
```
We then create the scatterplot matrix of all the variables, figuring out which variables have the biggest correlation with Medicare_Coverage. According to the graph, Los seems like the one with the highest correlation.

```{r}
fit1 <- lm(Medicare_Coverage~.,data=Train)
summary(fit1)
```

```{r}
aic<-step(fit1,direction='both')
```
```{r}
fit2<-lm(Medicare_Coverage ~ PW_GPCI + LOS,data=Train)
summary(fit2)
```
```{r}
sdres1 = rstandard(fit2)
yhat1 = fit1$fitted.values
plot(yhat1, sdres1)
```


```{r}
qqnorm(sdres1)
qqline(sdres1)
ggplot(data = data.frame(sdres1), aes(x = sdres1)) + geom_histogram(bins = 30) +
  ggtitle("Histogram MLS Plot")
```
```{r}
#Resfit <- resid(fit2)
#output1<-predict(fit2, se.fit = TRUE)
#ResfitValidation <- Medicare_Coverage - output1$fit
```
