---
title: Post 3 - Data for Equity
author: Guanchen Xiao, Fangzhou Cheng, Zehao Zhou, Yuke Li, Xuzhan Tan
date: '2022-10-27'
slug: []
categories: []
tags: []
description: ~
toc: yes
authors: []
series: []
lastmod: '2022-10-27T22:34:20-04:00'
featuredVideo: ~
featuredImage: ~
---
The dataset we are using is the Medicare Inpatient Hospitals by Provider and Service, which provides information on inpatient discharges for Medicare beneficiaries. We want to explore the data to see how well Medicare supports the health of the elderly and people with disabilities in each state and as a nation. We plan to examine the ratio of the amount covered by Medicare and total payment, which will help us to better understand the use and cost of healthcare. It adheres to beneficence and justice principles since the dataset collects information about vulnerable populations and analysis of the data might help to advance their interest. In addition,it follows the respect for person principle by making the data public while protecting personal information being disclosed.

Beneficence and Respect for persons are closely related. When collecting data, our data avoids collecting detailed personally identifiable information and other privacy. From a Beneficence perspective, we reduce the risk of information leakage to the people who provide it. At the same time, this approach is respectful to them. The detailed identifying information of each person in the data we study will not be necessary or helpful for our research, so there is no possibility of getting information about others through our data.

When publishing research findings, the beneficence approach is to carefully consider the potential impact of the published results. The impact of giving unethical results due to one-sided knowledge can be avoided to a certain extent by knowing the area where the data are collected. Asking for opinions and respecting others can help us achieve this beneficence, and presenting and informing the source of the data in the analysis allows more people to monitor our results and receive better opinions. For example, our data is not representative of the entire population. Some people may not be using Part A fee-for-service coverage, and hospitals may not be treating only patients with Part A fee-for-service coverage. Explaining and presenting this information makes our results more rational, while respecting the institutions and individuals who provided the information and avoiding negative consequences of the study results for them.

The dataset cannot represent the entire population that a hospital serves because it only includes information gathered for Medicare beneficiaries with Part A fee-for-service coverage, meaning that only individuals 65 years of age and older or younger people with disabilities and with End Stage Renal Disease are considered in the dataset. However, hospitals often treat many other patients with other kinds of coverages such as those covered with other public insurances (like the Federal Employees Health Benefits Program or Tricare), those with private health insurances (like Blue Cross and Blue Shield, Aetna, and Kaiser Permanente Insurance). Therefore, the beneficiaries of our analysis only involve patients with Medicare Part A coverage. Also, since all the information and data are provided by the hospital facilities, the dataset may not be 100% accurate, so analysis should be conducted carefully and conclusions should be made with qualification. Discuss the potential for abuse or misuse of the data.

Since our data is closely related to the amount of Medicare coverage for patients in the U.S, the impact of abuse and misuse of the data could be substantial. For example, one point we are focusing on is the percentage Medicare can cover for patients in each state. The preliminary results show an imbalance in resource allocation across the country. Some states have an extremely high coverage rate for patients while others are much lower than the average. For further usage, researchers should not just assess each state’s performance with the above data. Instead, they should put factors that are more state-specific into consideration. For referential, possible factors causing states to have lower Medicare coverage are the population of the state, the average income of the population, and the socioeconomic structure of the state. Also, the data is specifically focusing on the population aged over 65. The misuse of the data for another age group could also lead to potential issues in the future.
